In [1]:
!git clone https://github.com/vkhoi/KTH-Action-Recognition.git

Cloning into 'KTH-Action-Recognition'...
remote: Enumerating objects: 233, done.
remote: Total 233 (delta 0), reused 0 (delta 0), pack-reused 233
Receiving objects: 100% (233/233), 709.16 KiB | 15.76 MiB/s, done.
Resolving deltas: 100% (148/148), done.


In [3]:
%cd /content/KTH-Action-Recognition/dataset

/content/KTH-Action-Recognition/dataset


In [4]:
!ls

00sequences.txt  download.sh


In [ ]:
!wget http://www.nada.kth.se/cvap/actions/boxing.zip
#!wget http://www.nada.kth.se/cvap/actions/handclapping.zip
#!wget http://www.nada.kth.se/cvap/actions/handwaving.zip
#!wget http://www.nada.kth.se/cvap/actions/jogging.zip
#!wget http://www.nada.kth.se/cvap/actions/running.zip
#!wget http://www.nada.kth.se/cvap/actions/walking.zip

In [ ]:
!unzip boxing.zip -d boxing
!unzip handclapping.zip -d handclapping
!unzip handwaving.zip -d handwaving
!unzip jogging.zip -d jogging
!unzip running.zip -d running
!unzip walking.zip -d walking

!rm *.zip

Archive:  boxing.zip
  inflating: boxing/person01_boxing_d1_uncomp.avi  
  inflating: boxing/person01_boxing_d2_uncomp.avi  
  inflating: boxing/person01_boxing_d3_uncomp.avi  
  inflating: boxing/person01_boxing_d4_uncomp.avi  
  inflating: boxing/person02_boxing_d1_uncomp.avi  
  inflating: boxing/person02_boxing_d2_uncomp.avi  
  inflating: boxing/person02_boxing_d3_uncomp.avi  
  inflating: boxing/person02_boxing_d4_uncomp.avi  
  inflating: boxing/person03_boxing_d1_uncomp.avi  
  inflating: boxing/person03_boxing_d2_uncomp.avi  
  inflating: boxing/person03_boxing_d3_uncomp.avi  
  inflating: boxing/person03_boxing_d4_uncomp.avi  
  inflating: boxing/person04_boxing_d1_uncomp.avi  
  inflating: boxing/person04_boxing_d2_uncomp.avi  
  inflating: boxing/person04_boxing_d3_uncomp.avi  
  inflating: boxing/person04_boxing_d4_uncomp.avi  
  inflating: boxing/person05_boxing_d1_uncomp.avi  
  inflating: boxing/person05_boxing_d2_uncomp.avi  
  inflating: boxing/person05_boxing_d3_unco

In [ ]:
!python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/extract_optical_flow.py

Processing category boxing
Done 30 files
[mpeg4 @ 0x55e758758d80] ac-tex damaged at 8 6
[mpeg4 @ 0x55e758758d80] Error at MB: 74
Done 60 files
Done 90 files
Processing category handclapping
Done 120 files
Done 150 files
Done 180 files
Processing category handwaving
Done 210 files
Done 240 files
Done 270 files
Processing category jogging
Done 300 files
Done 330 files
Done 360 files
Done 390 files
Processing category running
Done 420 files
Done 450 files
Done 480 files
Processing category walking
Done 510 files
Done 540 files
Done 570 files


In [ ]:
import numpy as np
import os
import pickle

CATEGORIES = ["boxing", "handclapping", "handwaving", "jogging", "running", 
    "walking"]

# Dataset are divided according to the instruction at:
# http://www.nada.kth.se/cvap/actions/00sequences.txt
TRAIN_PEOPLE_ID = [11, 12, 13, 14, 15, 16, 17, 18]
DEV_PEOPLE_ID = [19, 20, 21, 23, 24, 25, 1, 4]
TEST_PEOPLE_ID = [22, 2, 3, 5, 6, 7, 8, 9, 10]

if __name__ == "__main__":

    train = []
    dev = []
    test = []

    # Store keypoints in training set.
    train_keypoints = []
    test_keypoints = []
    dev_keypoints = []

    for category in CATEGORIES:
        print("Processing category %s" % category)
        category_features = pickle.load(open("data/optflow_%s.p" % category, "rb"))

        for video in category_features:
            person_id = int(video["filename"].split("_")[0][6:])

            if person_id in TRAIN_PEOPLE_ID:
                train.append(video)

                for frame in video["features"]:
                    train_keypoints.append(frame)

            elif person_id in DEV_PEOPLE_ID:
                dev.append(video)
                for frame in video["features"]:
                    dev_keypoints.append(frame)
            else:
                test.append(video)
                for frame in video["features"]:
                    test_keypoints.append(frame)

    print("Saving train/dev/test set to files")
    pickle.dump(train, open("data/train.p", "wb"))
    pickle.dump(dev, open("data/dev.p", "wb"))
    pickle.dump(test, open("data/test.p", "wb"))

    print("Saving keypoints in training set")
    pickle.dump(train_keypoints, open("data/train_keypoints.p", "wb"))
    pickle.dump(dev_keypoints, open("data/dev_keypoints.p", "wb"))
    pickle.dump(test_keypoints, open("data/test_keypoints.p", "wb"))



In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/make_dataset.py

Processing category boxing
Processing category handclapping
Processing category handwaving
Processing category jogging
Processing category running
Processing category walking
Saving train/dev/test set to files
Saving keypoints in training set


In [ ]:
#Change output file name
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/clustering.py --dataset=data/train_keypoints.p --clusters=10

Loading dataset
Number of feature points to run clustering on: 96679
Running KMeans clustering
Initialization complete
Initialization complete
start iteration
done sorting
end inner loop
start iteration
done sorting
end inner loop
Iteration 0, inertia 11590263.390875867
start iteration
done sorting
Iteration 0, inertia 10812881.349547176
start iteration
done sorting
end inner loop
end inner loop
Iteration 1, inertia 10342493.721885748
start iteration
done sorting
end inner loop
Iteration 1, inertia 10223325.121064939
start iteration
done sorting
end inner loop
Iteration 2, inertia 10018171.717377663
start iteration
done sorting
end inner loop
Iteration 2, inertia 10059210.812010523
start iteration
done sorting
end inner loop
Iteration 3, inertia 9880694.741178313
start iteration
done sorting
end inner loop
Iteration 3, inertia 9967247.339748831
start iteration
done sorting
end inner loop
Iteration 4, inertia 9839094.707284098
start iteration
done sorting
end inner loop
Iteration 4, ine

In [ ]:
#Change output file name
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/clustering.py --dataset=data/test_keypoints.p --clusters=10

Loading dataset
Number of feature points to run clustering on: 102312
Running KMeans clustering
Initialization complete
Initialization complete
start iteration
done sorting
end inner loop
start iteration
done sorting
end inner loop
Iteration 0, inertia 10920052.20151381
start iteration
done sorting
end inner loop
Iteration 0, inertia 11343265.142327044
start iteration
done sorting
Iteration 1, inertia 10434749.825493561
start iteration
done sorting
end inner loop
end inner loop
Iteration 1, inertia 10707871.199663226
start iteration
done sorting
Iteration 2, inertia 10264114.379784716
start iteration
done sorting
end inner loop
end inner loop
Iteration 3, inertia 10179053.980206307
start iteration
done sorting
Iteration 2, inertia 10401211.431118278
start iteration
done sorting
end inner loop
end inner loop
Iteration 4, inertia 10123101.185047744
start iteration
done sorting
end inner loop
Iteration 3, inertia 10265802.064297834
start iteration
done sorting
end inner loop
Iteration 5, 

In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/make_bow_vector.py --codebook=data/cb_10clusters.p --tfidf=1 --dataset=data/train.p --output=data/train_bow_c10.p

Make bow vector for each frame
Applying TF-IDF weighting
Processed 50/191 videos
Processed 100/191 videos
Processed 150/191 videos


In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/make_bow_vector.py --codebook=data/cbtest_10clusters.p --tfidf=1 --dataset=data/test.p --output=data/test_bow_c10.p

Make bow vector for each frame
Applying TF-IDF weighting
Processed 50/216 videos
Processed 100/216 videos
Processed 150/216 videos
Processed 200/216 videos


In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/train_svm.py --dataset_bow=data/train_bow_c10.p --C=1 --output=data/svm_C10_c10.p

...............................................................................................................................................................................*........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/evaluate.py --svm_file=data/svm_C10_c10.p --bow_file=data/test_bow_c10.p

62/216 Correct
Accuracy = 0.28703703703703703
Confusion matrix
[[32. 35. 33.  0.  0.  6.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 3.  1.  2.  3. 13.  3.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1. 33. 23. 27.]]


In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/evaluate.py --svm_file=data/svm_C2_c2.p --bow_file=data/train_bow_c2.p

75/191 Correct
Accuracy = 0.39267015706806285
Confusion matrix
[[25. 21. 16.  1.  8.  1.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 1.  4.  7. 25. 21.  7.]
 [ 0.  1.  2.  0.  2.  1.]
 [ 6.  5.  7.  6.  1. 23.]]


In [ ]:
! python /content/KTH-Action-Recognition/baseline_optflow_bow_svm/evaluate.py --svm_file=data/svm_C10_c10.p --bow_file=data/test_bow_c10.p

31/216 Correct
Accuracy = 0.14351851851851852
Confusion matrix
[[ 0.  6.  0.  0.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.]
 [33. 28. 35.  3.  2.  9.]
 [ 0.  0.  0. 33. 34. 27.]]
