In [1]:
!wget --no-check-certificate "https://www.crcv.ucf.edu/data/UCF101/UCF101.rar"
!unrar x UCF101.rar -inul -y
!rm *.rar

--2021-10-02 15:58:01--  https://www.crcv.ucf.edu/data/UCF101/UCF101.rar
Resolving www.crcv.ucf.edu (www.crcv.ucf.edu)... 132.170.214.127
Connecting to www.crcv.ucf.edu (www.crcv.ucf.edu)|132.170.214.127|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 6932971618 (6.5G) [application/rar]
Saving to: ‘UCF101.rar’

UCF101.rar            3%[                    ] 256.05M  27.1MB/s    in 10s     

2021-10-02 15:58:11 (25.4 MB/s) - Connection closed at byte 268484125. Retrying.

--2021-10-02 15:58:12--  (try: 2)  https://www.crcv.ucf.edu/data/UCF101/UCF101.rar
Connecting to www.crcv.ucf.edu (www.crcv.ucf.edu)|132.170.214.127|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 206 Partial Content
Length: 6932971618 (6.5G), 6664487493 (6.2G) remaining [application/rar]
Saving to: ‘UCF101.rar’

UCF101.rar          100%[===================>]   6.46G  27.0MB/s    in

In [6]:
import shutil

source_dir = r"/content/UCF-101/ApplyEyeMakeup"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

'/content/video_data/ApplyEyeMakeup'

In [7]:
import shutil

source_dir = r"/content/UCF-101/ApplyLipstick"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

'/content/video_data/ApplyLipstick'

In [8]:
import shutil

source_dir = r"/content/UCF-101/Archery"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

'/content/video_data/Archery'

In [9]:
import shutil

source_dir = r"/content/UCF-101/BabyCrawling"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

'/content/video_data/BabyCrawling'

In [10]:
import shutil

source_dir = r"/content/UCF-101/BalanceBeam"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

'/content/video_data/BalanceBeam'

In [2]:
#MAKE a folder video_data
import shutil

source_dir = r"/content/UCF-101/Biking"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

import shutil

source_dir = r"/content/UCF-101/JumpingJack"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

import shutil

source_dir = r"/content/UCF-101/Kayaking"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

source_dir = r"/content/UCF-101/PlayingGuitar"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

source_dir = r"/content/UCF-101/Rowing"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

source_dir = r"/content/UCF-101/Skijet"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)

source_dir = r"/content/UCF-101/TaiChi"
destination_dir = r"/content/video_data"
shutil.move(source_dir, destination_dir)




'/content/video_data/TaiChi'

In [3]:
import shutil
shutil.rmtree("/content/UCF-101")

In [4]:
data_dir = "/content/video_data"
img_height , img_width = 64, 64
seq_len = 70
 
#classes = ["ApplyEyeMakeup", "Archery", "ApplyLipstick", "BabyCrawling", "BalanceBeam", "BandMarching"]
classes = ["Biking", "JumpingJack", "Kayaking", "PlayingGuitar", "Rowing", "Skijet", "TaiChi"]

In [13]:
import cv2

def frames_extraction(video_path):
    frames_list = []
     
    vidObj = cv2.VideoCapture(video_path)
    # Used as counter variable 
    count = 1
 
    while count <= seq_len: 
         
        success, image = vidObj.read() 
        if success:
            image = cv2.resize(image, (img_height, img_width))
            frames_list.append(image)
            count += 1
        else:
            print("Defected frame")
            break
 
            
    return frames_list

In [15]:
import os
import numpy as np

X = []
Y = []
input_dir = data_dir
  
classes_list = os.listdir(input_dir)
  
for c in classes_list:
    print(c)
    files_list = os.listdir(os.path.join(input_dir, c))
    #print(files_list)
    for f in files_list:
      #print(f)
      file_name = os.path.join(os.path.join(input_dir, c), f)
      print(file_name)
      frames = frames_extraction(os.path.join(os.path.join(input_dir, c), f))
      if len(frames) == seq_len:
          X.append(frames)
        
          y = [0]*len(classes_list)
          y[classes_list.index(c)] = 1
          Y.append(y)

X = np.asarray(X)
Y = np.asarray(Y)

BabyCrawling
/content/video_data/BabyCrawling/v_BabyCrawling_g14_c03.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g16_c03.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g18_c06.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g17_c01.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g22_c01.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g12_c03.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g10_c05.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g15_c06.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g11_c02.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g07_c02.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g24_c02.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g11_c01.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g15_c02.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g13_c02.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g07_c03.avi
/content/video_data/BabyCrawling/v_BabyCrawling_g04_c02.avi
/content/video_data/BabyCra

In [18]:
def create_data(input_dir):
    X = []
    Y = []
     
    classes_list = os.listdir(input_dir)
     
    for c in classes_list:
        print(c)
        files_list = os.listdir(os.path.join(input_dir, c))
        for f in files_list:
          frames = frames_extraction(os.path.join(os.path.join(input_dir, c), f))
          if len(frames) == seq_len:
            X.append(frames)
          
            y = [0]*len(classes)
            y[classes.index(c)] = 1
            Y.append(y)
     
    X = np.asarray(X)
    Y = np.asarray(Y)
    return X, Y

In [6]:
import keras
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model 
from keras.layers import *
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping
 
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
#import keras_metrics as km
from tensorflow.python.keras.metrics import Metric
 
 
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import multilabel_confusion_matrix
 
data_dir = "video_data/"
img_height , img_width = 64, 64
seq_len = 70
 
classes = ["Biking", "JumpingJack", "Kayaking", "PlayingGuitar", "Rowing", "Skijet", "TaiChi"]
 
#  Creating frames from videos
 
def frames_extraction(video_path):
    frames_list = []
     
    vidObj = cv2.VideoCapture(video_path)
    # Used as counter variable 
    count = 1
 
    while count <= seq_len: 
         
        success, image = vidObj.read() 
        if success:
            image = cv2.resize(image, (img_height, img_width))
            frames_list.append(image)
            count += 1
        else:
            print("Defected frame")
            break
 
            
    return frames_list
 
def create_data(input_dir):
    X = []
    Y = []
     
    classes_list = os.listdir(input_dir)
     
    for c in classes_list:
        print(c)
        files_list = os.listdir(os.path.join(input_dir, c))
        for f in files_list:
          frames = frames_extraction(os.path.join(os.path.join(input_dir, c), f))
          if len(frames) == seq_len:
            X.append(frames)
          
            y = [0]*len(classes)
            y[classes.index(c)] = 1
            Y.append(y)
     
    X = np.asarray(X)
    Y = np.asarray(Y)
    return X, Y
 
X, Y = create_data(data_dir)
 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, shuffle=True, random_state=0)
 
model = Sequential()
model.add(ConvLSTM2D(filters = 64, kernel_size = (3, 3), return_sequences = False, data_format = "channels_last", input_shape = (seq_len, img_height, img_width, 3)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(256, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(7, activation = "softmax"))
 
model.summary()
 
#opt = keras.optimizers.adam_v2(learning_rate=0.01)
model.compile(loss='categorical_crossentropy', optimizer= 'Adam', metrics=["accuracy"])
 
earlystop = EarlyStopping(patience=7)
callbacks = [earlystop]
 
history = model.fit(x = X_train, y = y_train, epochs=10, batch_size = 8 , shuffle=True, validation_split=0.2, callbacks=callbacks)
 
y_pred = np.argmax(y_pred, axis = 1)
y_test = np.argmax(y_test, axis = 1)
 
print(classification_report(y_test, y_pred))


Skijet
Rowing
Kayaking
JumpingJack
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Biking
PlayingGuitar
TaiChi
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv_lst_m2d_1 (ConvLSTM2D)  (None, 62, 62, 64)        154624    
_________________________________________________________________
dropout_2 (Dropout)          (None, 62, 62, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 246016)            0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               62980352  
____________________________________

ResourceExhaustedError: ignored

In [7]:
import keras
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model 
from keras.layers import *
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping
 
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
#import keras_metrics as km
from tensorflow.python.keras.metrics import Metric
 
 
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import multilabel_confusion_matrix
 
data_dir = "video_data/"
img_height , img_width = 64, 64
seq_len = 70
 
classes = ["Biking", "JumpingJack", "Kayaking", "PlayingGuitar", "Rowing", "Skijet", "TaiChi"]
 
#  Creating frames from videos
 
def frames_extraction(video_path):
    frames_list = []
     
    vidObj = cv2.VideoCapture(video_path)
    # Used as counter variable 
    count = 1
 
    while count <= seq_len: 
         
        success, image = vidObj.read() 
        if success:
            image = cv2.resize(image, (img_height, img_width))
            frames_list.append(image)
            count += 1
        else:
            print("Defected frame")
            break
 
            
    return frames_list
 
def create_data(input_dir):
    X = []
    Y = []
     
    classes_list = os.listdir(input_dir)
     
    for c in classes_list:
        print(c)
        files_list = os.listdir(os.path.join(input_dir, c))
        for f in files_list:
          frames = frames_extraction(os.path.join(os.path.join(input_dir, c), f))
          if len(frames) == seq_len:
            X.append(frames)
          
            y = [0]*len(classes)
            y[classes.index(c)] = 1
            Y.append(y)
     
    X = np.asarray(X)
    Y = np.asarray(Y)
    return X, Y
 
X, Y = create_data(data_dir)
 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, shuffle=True, random_state=0)
 
model = Sequential()
model.add(ConvLSTM2D(filters = 64, kernel_size = (3, 3), return_sequences = False, data_format = "channels_last", input_shape = (seq_len, img_height, img_width, 3)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(256, activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(7, activation = "softmax"))
 
model.summary()

#You can try reducing trainable parameters by using some 
#form of Transfer Learning - try freezing the initial few layers and use lower batch sizes.


Skijet
Rowing
Kayaking
JumpingJack
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Defected frame
Biking
PlayingGuitar
TaiChi
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv_lst_m2d_2 (ConvLSTM2D)  (None, 62, 62, 64)        154624    
_________________________________________________________________
dropout_4 (Dropout)          (None, 62, 62, 64)        0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 246016)            0         
_________________________________________________________________
dense_4 (Dense)              (None, 256)               62980352  
____________________________________

In [10]:
model.compile(loss='categorical_crossentropy', optimizer= 'Adam', metrics=["accuracy"])
 
earlystop = EarlyStopping(patience=7)
callbacks = [earlystop]
 
#history = model.fit(x = X_train, y = y_train, epochs=10, batch_size = 8 , shuffle=True, validation_split=0.2, callbacks=callbacks)
model.fit(x = X_train, y = y_train, epochs=10, batch_size = 4, validation_data=(X_test, y_test))

Epoch 1/10
175/175 [==============================] - 307s 2s/step - loss: 7.4218 - accuracy: 0.3157 - val_loss: 1.7514 - val_accuracy: 0.3409
Epoch 2/10
175/175 [==============================] - 304s 2s/step - loss: 1.6655 - accuracy: 0.3843 - val_loss: 1.3182 - val_accuracy: 0.4205
Epoch 3/10
175/175 [==============================] - 323s 2s/step - loss: 1.5951 - accuracy: 0.4014 - val_loss: 1.3203 - val_accuracy: 0.4659
Epoch 4/10
175/175 [==============================] - 304s 2s/step - loss: 1.4071 - accuracy: 0.4714 - val_loss: 1.4862 - val_accuracy: 0.4773
Epoch 5/10
175/175 [==============================] - 303s 2s/step - loss: 1.4053 - accuracy: 0.4900 - val_loss: 1.3201 - val_accuracy: 0.4602
Epoch 6/10
175/175 [==============================] - 323s 2s/step - loss: 1.5855 - accuracy: 0.4686 - val_loss: 1.3047 - val_accuracy: 0.4489
Epoch 7/10
175/175 [==============================] - 304s 2s/step - loss: 1.2917 - accuracy: 0.5143 - val_loss: 1.1275 - val_accuracy: 0.5852

In [11]:
model_name = f'dstmv1.h5'

# Saving your Model
model.save(model_name)

In [14]:
X = []
file_name = "/content/video_data/Biking/v_Biking_g01_c01.avi"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape

/content/video_data/Biking/v_Biking_g01_c01.avi


(1, 70, 64, 64, 3)

In [15]:
model.predict(X)

array([[0.36452016, 0.04663532, 0.17681876, 0.04261288, 0.12740387,
        0.17078869, 0.07122035]], dtype=float32)

In [16]:
X = []
file_name = "/content/video_data/JumpingJack/v_JumpingJack_g01_c01.avi"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape
model.predict(X)

/content/video_data/JumpingJack/v_JumpingJack_g01_c01.avi


array([[2.1179019e-08, 9.9798298e-01, 1.0098676e-05, 1.4519725e-09,
        9.9800227e-06, 1.9888936e-03, 7.9653473e-06]], dtype=float32)

In [20]:
seq_len = 4
X = []
file_name = "/content/Biking5.mp4"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape
model.predict(X)[0]

/content/Biking5.mp4


array([0.22048259, 0.03346183, 0.26797882, 0.0072048 , 0.0981154 ,
       0.30617672, 0.0665798 ], dtype=float32)

In [39]:
seq_len = 5
X = []
file_name = "/content/Biking7.mp4"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape
model.predict(X)[0]

/content/Biking7.mp4


array([0.3026849 , 0.07289524, 0.12338648, 0.16054401, 0.14772639,
       0.10598078, 0.08678219], dtype=float32)

In [36]:
seq_len = 5
X = []
file_name = "/content/Biking5.mp4"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape
model.predict(X)[0]

/content/Biking5.mp4


array([0.38431373, 0.05454196, 0.0829739 , 0.22460786, 0.12553029,
       0.06689314, 0.06113907], dtype=float32)

In [40]:
seq_len = 70
X = []
file_name = "/content/video_data/Biking/v_Biking_g01_c01.avi"
print(file_name)
frames = frames_extraction(file_name)
if len(frames) == seq_len:
  X.append(frames)
X = np.asarray(X)

X.shape
model.predict(X)[0]

features_layer1 = keras.models.Model(inputs=model.input, outputs=model.get_layer("dense_4").output)

print(features_layer1.predict(X)[0])

#model.layers[4] 

/content/video_data/Biking/v_Biking_g01_c01.avi
[ 0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.       31.368008  0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        9.864178
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.        0.        0.        0.
  0.        0.        0.        0.  

In [30]:
features_layer1 = keras.models.Model(inputs=model.inputs, outputs=model.get_layer("dropout_5").output)

print(features_layer1)